# Generated by Django 5.0.1 on 2024-02-24 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expressions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, unique=True)),
                ('translation_it', models.CharField(max_length=50, null=True)),
                ('note', models.CharField(max_length=300, null=True)),
                ('context', models.CharField(max_length=30, null=True)),
                ('example_en', models.CharField(max_length=150, null=True)),
                ('example_it', models.CharField(max_length=150, null=True)),
                ('is_phrasal_verb', models.BooleanField(default=False)),
                ('is_formal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('level', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.IntegerField(default=0)),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocapp.expressions')),
            ],
        ),
        migrations.AddField(
            model_name='expressions',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocapp.levels'),
        ),
        migrations.AddField(
            model_name='expressions',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocapp.roles'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('last_connection', models.DateTimeField(verbose_name='last connection')),
                ('expression', models.ManyToManyField(through='vocapp.Learn', to='vocapp.expressions')),
            ],
        ),
        migrations.AddField(
            model_name='learn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocapp.users'),
        ),
    ]
