# Generated by Django 5.0.1 on 2024-08-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='content',
            field=models.CharField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='expression',
            name='context',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expression',
            name='example_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expression',
            name='example_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expression',
            name='note',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='expression',
            name='translation_it',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
