# Generated by Django 5.0.1 on 2024-08-26 21:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocapp', '0002_alter_expression_content_alter_expression_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, max_length=350, validators=[django.core.validators.MaxLengthValidator(350)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocapp.expression')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
